DEBUG:__main__:File : queries-uniform-5-multi_True-density
(388800, 11)
RMSE : 45.183093925228356
Fitting : 0.9678981305512343
Traceback (most recent call last):
  File "model_training.py", line 66, in <module>
    with open(pkl_filename, 'wb') as file:  
FileNotFoundError: [Errno 2] No such file or directory: '../models/queries-uniform-5-multi_True-density-XGB-RMSE=45.18-R2=0.97.pkl'
